version: "3.3"
services:

  portainer:
    image: portainer/portainer-ce:2.6.3
    command: -H unix:///var/run/docker.sock
    env_file:
      - ../.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000

volumes:
  portainer_data:
